version: "3.7"
services:
  redis:
    image: redis:6-buster
    ports:
      - "6379:6379"
  api:
    build:
      context: src
      dockerfile: app/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - redis
      - worker
  worker:
    build:
      context: src
      dockerfile: worker/Dockerfile
    depends_on:
      - redis
